language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.22.0

script:
  - cargo generate-lockfile --verbose
  - cargo update -p cc --precise "1.0.41" --verbose
  - cargo build --verbose
  - cargo test --verbose

